### ISSUE TITLE
Docker container does not start

### ISSUE THREAD

**Issue by brutaldev** [linuxserver/docker-headphones#2]
This image does not seem to start at all with no error log details.

Using the `docker logs -f Headphones` command just keeps on logging the following message:

```
IOError: [Errno 2] No such file or directory: '/etc/service/headphones/None/headphones.log'
Unable to create the log directory. Logging to screen only.
Traceback (most recent call last):
  File "/app/headphones/Headphones.py", line 223, in <module>
    main()
  File "/app/headphones/Headphones.py", line 155, in main
    headphones.initialize(config_file)
  File "/app/headphones/headphones/__init__.py", line 138, in initialize
    verbose=VERBOSE)
  File "/app/headphones/headphones/logger.py", line 153, in initLogger
    file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, backupCount=MAX_FILES)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/etc/service/headphones/None/headphones.log'

```

I only get the following log during startup:

```
-----------------------------------
GID/UID
-----------------------------------
User uid: 911
User gid: 8378
-----------------------------------

(Reading database ... 16767 files and directories currently installed.)
Preparing to unpack .../ffmpeg_7%3a2.7.2+git4~trusty_amd64.deb ...
Unpacking ffmpeg (7:2.7.2+git4~trusty) over (7:2.7.2+git3~trusty) ...
Setting up ffmpeg (7:2.7.2+git4~trusty) ...
Sep 12 22:48:25 11766a392633 syslog-ng[82]: syslog-ng starting up; version='3.5.3'
```

Any idea what is going on here?

**Comment by lonix** [comment]
I shall look into this :)

**Comment by smdion** [comment]
Hey Brutal dev,

Sorry for the delay on this. What is log_dir = set to in  your config?

**Comment by brutaldev** [comment]
Hey @smdion 

The config value is `log_dir = /config/logs`. There is a volume mapping to `/config` and there are logs in there.

I cannot reproduce this anymore though, I have everything working, but to fix it I had to scrap all the config, cache and databases and start from scratch. When deleting everything in the config folder the docker did start up successfully, it just didn't like it when I had pre-existing configuration in there.

So you could close this issue I guess although the workaround is a bit heavy handed.
