### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'

### ISSUE THREAD

**Issue by davelund750** [linuxserver/docker-headphones#43]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04

Using a a shared .env file to set  shared environment variables in all my ls.io docker images.
```
TZ="America/Indiana/Indianapolis"
PGID=1000
PUID=1000
```

```
headphones_1          | Traceback (most recent call last):
headphones_1          |   File "/app/headphones/Headphones.py", line 23, in <module>
headphones_1          |     from headphones import webstart, logger
headphones_1          |   File "/app/headphones/headphones/__init__.py", line 68, in <module>
headphones_1          |     SCHED = BackgroundScheduler()
headphones_1          |   File "/app/headphones/lib/apscheduler/schedulers/base.py", line 61, in __init__
headphones_1          |     self.configure(gconfig, **options)
headphones_1          |   File "/app/headphones/lib/apscheduler/schedulers/base.py", line 95, in configure
headphones_1          |     self._configure(config)
headphones_1          |   File "/app/headphones/lib/apscheduler/schedulers/background.py", line 27, in _configure
headphones_1          |     super(BackgroundScheduler, self)._configure(config)
headphones_1          |   File "/app/headphones/lib/apscheduler/schedulers/base.py", line 576, in _configure
headphones_1          |     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
headphones_1          |   File "/app/headphones/lib/tzlocal/unix.py", line 108, in get_localzone
headphones_1          |     _cache_tz = _get_localzone()
headphones_1          |   File "/app/headphones/lib/tzlocal/unix.py", line 102, in _get_localzone
headphones_1          |     raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
headphones_1          | pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

**Comment by sparklyballs** [comment]
works fine here....

```
sparklyballs@testbed:~$ docker run --name=test -d -e TZ=America/Indiana/Indianapolis --net=host linuxserver/headphones
cf78e2a2d781f1480e57190bafe02b7ce17b7146b79cae93994a3b0a1e58be48
sparklyballs@testbed:~$ docker logs -f test
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
26-Mar-2019 09:11:10 - INFO :: MainThread : Checking to see if the database has all tables....
26-Mar-2019 09:11:11 - INFO :: MainThread : Retrieving latest version information from GitHub
26-Mar-2019 09:11:11 - INFO :: MainThread : Headphones is up to date
26-Mar-2019 09:11:11 - INFO :: MainThread : Starting Headphones web server on http://0.0.0.0:8181/
26-Mar-2019 09:11:11 - INFO :: MainThread : Scheduled background task: Search for Wanted
26-Mar-2019 09:11:11 - INFO :: MainThread : Scheduled background task: Download Scan
26-Mar-2019 09:11:11 - INFO :: MainThread : Scheduled background task: Library Scan
26-Mar-2019 09:11:11 - INFO :: MainThread : Scheduled background task: MusicBrainz Update
26-Mar-2019 09:11:11 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
```

i'm in the uk and it's currently 1:12 pm...

**Comment by sparklyballs** [comment]
i get that error if i do not specify a timezone, i.e

`docker run --name=test -d --net=host linuxserver/headphones`

so it would seem your delivery method of the env setting is not right somehow. 

and on a side note, it should perhaps be mentioned in the README that setting a TZ is mandatory.

**Comment by b0red** [comment]
I get the same error, and I have a TZ settings.
in environment:
 - TZ´=${TZ}

This settings works in other linuxserver docker images. Havent changed anything for a long time and this container worked before. Can't say when it stopped working though.

**Comment by aptalca** [comment]
Why do you have a tick symbol after TZ? And what is your TZ variable actually set to? `${TZ}` means nothing to us.

**Comment by thelamer** [comment]
We added the container to default to UTC, if you are having problems with your time code please copy and paste it exactly from this page: 
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Or leave it out and use UTC

**Comment by b0red** [comment]
> Why do you have a tick symbol after TZ? And what is your TZ variable actually set to? `${TZ}` means nothing to us.

The tick was a typy, and my TZ variable is set to "Europe/Stockholm"
